import {
  Search, Eye, EyeOff, AlertCircle, Calendar,
  ChevronRight, ChevronLeft, ChevronUp, ChevronDown,
  ArrowRight, ArrowLeft, ArrowUp, ArrowDown,
  Plus, Minus, X, Check,
  Copy, Save, Trash2, Edit2, Filter, Download, Upload,
  Percent, Coins, Wallet, CreditCard,
  MoreHorizontal, Phone, Lock,
  FileText, Link as LinkIcon,
  ArrowUpAZ, Loader2,
  CircleX, Info, CircleCheck,
} from 'lucide-react';

/**
 * Mapa de iconos único de la librería — union de los mapas antes duplicados
 * en Button.jsx y _inputBase.js. Toda clave doble (PascalCase + kebab-case)
 * apunta al mismo componente Lucide.
 */
export const ICONS = {
  Search, 'search': Search,
  Eye, 'eye': Eye,
  EyeOff, 'eye-off': EyeOff,
  AlertCircle, 'alert-circle': AlertCircle,
  Calendar, 'calendar': Calendar,
  ChevronRight, 'chevron-right': ChevronRight,
  ChevronLeft,  'chevron-left':  ChevronLeft,
  ChevronUp,    'chevron-up':    ChevronUp,
  ChevronDown,  'chevron-down':  ChevronDown,
  ArrowRight, 'arrow-right': ArrowRight,
  ArrowLeft,  'arrow-left':  ArrowLeft,
  ArrowUp,    'arrow-up':    ArrowUp,
  ArrowDown,  'arrow-down':  ArrowDown,
  Plus, 'plus': Plus,
  Minus, 'minus': Minus,
  X, 'x': X,
  Check, 'check': Check,
  Copy, 'copy': Copy,
  Save, 'save': Save,
  Delete: Trash2, 'delete': Trash2, 'trash': Trash2,
  Edit2, 'edit2': Edit2, 'edit': Edit2,
  Filter, 'filter': Filter,
  Download, 'download': Download,
  Upload, 'upload': Upload,
  Percent, 'percent': Percent,
  Coins, 'coins': Coins,
  Wallet, 'wallet': Wallet,
  CreditCard, 'credit-card': CreditCard,
  MoreHorizontal, 'more': MoreHorizontal,
  Phone, 'phone': Phone,
  Lock, 'lock': Lock,
  FileText, 'file-text': FileText,
  LinkIcon, 'link': LinkIcon,
  ArrowUpAZ, 'arrow-up-az': ArrowUpAZ,
  Loader2, 'loader': Loader2,
  CircleX, 'circle-x': CircleX,
  Info, 'info': Info,
  CircleCheck, 'circle-check': CircleCheck,
};
